//go:build magicgen

package board

import (
	"bytes"
	"fmt"
	"math/rand/v2"
)

const maxMagicGenAttempts = 100_000_000

func GenerateMagics() ([]byte, error) {
	rnd := rand.New(rand.NewPCG(0x8008, 0x135)) // teehee

	w := bytes.NewBuffer(nil)

	fmt.Fprintln(w, `// Code generated by 'make generate'; DO NOT EDIT.
//
//go:generate go run -tags magicgen magicgen/main.go
package board

var (
  rookMagicNumbers   = [64]uint64{`)

	for sq := A1; sq <= H8; sq++ {
		fmt.Fprint(w, "    0x")
		mask := computeRelevantOccupancyMask(sq, rookDirections)
		n := mask.Count()
		shift := 64 - n

		scratch := make([]Bitboard, 1<<n)
		stamp := make([]int, 1<<n)

		pairs := computeOccupancyAttacks(sq, rookDirections)
		attempt := 0

		var found bool
		for attempt < maxMagicGenAttempts {
			candidate := rnd.Uint64() & rnd.Uint64() & rnd.Uint64() // 1/8 probability of each bit being set
			// early rejection, bits barely moved
			if Bitboard((uint64(mask)*candidate)>>56).Count() < 6 {
				continue
			}
			attempt++

			abandoned := false
			for _, pair := range pairs {
				idx := int((uint64(pair.occupancy) * candidate) >> shift)
				if stamp[idx] != attempt {
					stamp[idx] = attempt
					scratch[idx] = pair.attacks
				} else if scratch[idx] != pair.attacks {
					abandoned = true
					break
				}
			}

			if abandoned {
				continue
			}

			fmt.Fprintf(w, "%016x", candidate)
			found = true
			break
		}

		if !found {
			return nil, fmt.Errorf("failed to find rook magic for square %s after %d attempts", sq, attempt)
		}

		fmt.Fprint(w, ",\n")
	}

	fmt.Fprintln(w, `  }

  bishopMagicNumbers = [64]uint64{`)

	for sq := A1; sq <= H8; sq++ {
		fmt.Fprint(w, "    0x")
		mask := computeRelevantOccupancyMask(sq, bishopDirections)
		n := mask.Count()
		shift := 64 - n

		scratch := make([]Bitboard, 1<<n)
		stamp := make([]int, 1<<n)

		pairs := computeOccupancyAttacks(sq, bishopDirections)
		attempt := 0

		var found bool
		for attempt < maxMagicGenAttempts {
			candidate := rnd.Uint64() & rnd.Uint64() & rnd.Uint64() // 1/8 probability of each bit being set
			// early rejection, bits barely moved
			if Bitboard((uint64(mask)*candidate)>>56).Count() < 6 {
				continue
			}
			attempt++

			abandoned := false
			for _, pair := range pairs {
				idx := int((uint64(pair.occupancy) * candidate) >> shift)
				if stamp[idx] != attempt {
					stamp[idx] = attempt
					scratch[idx] = pair.attacks
				} else if scratch[idx] != pair.attacks {
					abandoned = true
					break
				}
			}

			if abandoned {
				continue
			}

			fmt.Fprintf(w, "%016x", candidate)
			found = true
			break
		}

		if !found {
			return nil, fmt.Errorf("failed to find bishop magic for square %s after %d attempts", sq, attempt)
		}

		fmt.Fprint(w, ",\n")
	}

	fmt.Fprintln(w, `  }`)

	fmt.Fprintln(w, `)`)
	return w.Bytes(), nil
}
